### PR TITLE
backend

### PR DESCRIPTION
**Pull request by Vikram9866**
@cfelton . 
This PR Contains BackEnd (runs paralelly).
Once FrontEnd have a block processed, it will send the `start` signal and once the backend is ready to take next block, it will assert `ready` signal.

Code clean up for quantizer module and some small Fixes.

### CODE REVIEW

**Comment by mkatsimpris** [comment]
Hello @Vikram9866. As my processing is continuous and it never stops. I think it would be better to put a fifo  before the module which stops the processing. So, you can store there the data until the ready signals is valid again. Also, why is there a FIFO before the quantizer?

@cfelton  what do you think?

**Comment by Vikram9866** [comment]
@mkatsimpris. The backend takes data from a `Dual Port RAM`. Front end can store data in that `RAM`.

**Comment by mkatsimpris** [comment]
@Vikram9866 You can take the data serially from the frontend right? And I store it in a RAM, so I dont halt my processing right?

**Comment by Vikram9866** [comment]
@mkatsimpris . You store the 1st block in the DualPort RAM. Then process your second block. FrontEnd needs to stop processing if `backend` does not send ready signal to `frontend`.

The use of RAM before `Quantizer` is mainly to process all the sub modules parallely.

**Comment by mkatsimpris** [comment]
Can you make the ram big enough to handle all the incoming data without to stop my processing?

**Comment by mkatsimpris** [comment]
You can add 2 or three rams to store the other blocks (Cb, Cr). So when I write to your rams I dont overlap with data you havent read yet.

**Comment by mkatsimpris** [comment]
@Vikram9866 I checked your PR and I have some concerns please respond ASAP:

1) In the test_backend.py you dont test the outputs of your backend part with the outputs of a software prototype. You just assign some values in the input signals.

2)There isnt a convertible testbench implemented.

**Comment by Vikram9866** [comment]
@mkatsimpris . `data_out` is the `output data` as seen from the ports. I did not add the software prototype(need to merge all sub-modules) yet as some work have to be done in it.

Also, I have been checking if my module is convertible. I am not checking by sending particular `test cases`(`in conversion bench`).

**Comment by Vikram9866** [comment]
@mkatsimpris . The input RAM in quantizer have enough space to store two blocks. I do not think it will halt your processing (for most of the test cases).

**Comment by cfelton** [comment]
The overall flow seems to be unclear still.  The current test setup is defined to stream an image into the frontend at max rate (clock rate), that is one pixel per clock cycle.  @mkatsimpris indicated the frontend maintains this rate (output for every input).  @mkatsimpris is this accurate?  Or is it actually slower because because it reads a block three times (essentially halts the input stream)? 

The current frontend doesn't have the flow control for the proposed three buffer to work the backend needs to be able to maintain the same rate (or faster), is this true?

**Comment by cfelton** [comment]
@Vikram9866 I agree with @mkatsimpris your testbench needs to compare the outputs of the software model and should have at least a minimal convertible testbench (a testbench that tests conversion).

**Comment by mkatsimpris** [comment]
@cfelton In order for my frontend processing to be continuous i designed the triple block buffer which stores the inputs of the video source. Because I have to read each block three times the triple buffer have 4 rams to store the input data in order not to overlap with data that havent been read yet. So the output of the block buffer is a continuous stream of pixel per clock cycle. The triple buffer outputs a stop_source signals which forces the video inputs to stop inputing data. We this module we can have the same clock rate in the video source and the frontend part

**Comment by mkatsimpris** [comment]
@Vikram9866  i will add a buffer after my frontend in order to integrate the ready-valid handshake with your part. I would like to know what will be the maximum delay from ready = '0' to ready = '1'. This is importand because it will define how big the buffer should be.

**Comment by Vikram9866** [comment]
@mkatsimpris . The worst case will make back-end to toggle ready-signal from 0 to 1 in 120 `clock cycles` (for general images there will me many zeroes after `DCT` compression so it may be around 70 ).

Also, I have added a RAM before back-end that stores 128 pixels. So, I think there wont be need for extra Buffer.

@cfelton . I still need to do some work on software prototype. So, I dint add it yet. I will add few tests to convertible bench also.

**Comment by Vikram9866** [comment]
@mkatsimpris . The worst case will make back-end to toggle ready-signal from 0 to 1 in 120 `clock cycles` (for general images there will me many zeroes after `DCT` compression so it may be around 70 ).

Also, I have added a RAM before back-end that stores 128 pixels. So, I think there wont be need for extra Buffer.

@cfelton . I still need to do some work on software prototype. So, I dint add it yet. I will add few tests to convertible bench also.

**Comment by mkatsimpris** [comment]
Vikram thanks for the infos.

**Comment by mkatsimpris** [comment]
@Vikram9866  you mentioned that your backend stores the data in a buffer in order to process it parallely. By parallely you mean to process the entire block (64 signals)? Because I converted my parallel outputs of the zig-zag module to serial in order to be consistent with the input flow of your backend (in previous discussions you told me that you want serially each signal of the block).

**Comment by Vikram9866** [comment]
@mkatsimpris . `Front-end` stores data into a `RAM`. I access data one by one from the `RAM`(spacing 128 inputs).

By parallely I mean that when last module in Back-end processes `n th block`. The module before the last one processes `n-1 st block` and so on.

1 block = 8x8 Pixels(64 pixels).

The main purpose of buffer between each block is to make each module work parallely. i.e when one module reads from the buffer other can write into the same buffer.

I am using double buffer's in my design for this purpose.

**Comment by mkatsimpris** [comment]
ok @Vikram9866. So there is no need to add a buffer after my frontend?

**Comment by Vikram9866** [comment]
I have already added a `buffer` before `back-end` merk. So you dont need to.

**Comment by mkatsimpris** [comment]
@Vikram9866 in order to process the first block it takes ~290 cycles. For the next blocks till the last block the processing of each block takes exactly 64 cycles. Have you taken this into consideration?

**Comment by Vikram9866** [comment]
@mkatsimpris . This may cause problem (may overwrite data that front-end writes in RAM). It will be good if I increase the RAM size from `128` to `128 + 64`. 

So that `front-end` do not need to stop its work..

**Comment by mkatsimpris** [comment]
Yes thats the solution! Do you have as parameter the size of the ram in your design?

**Comment by Vikram9866** [comment]
`dram(clock, data_in, write_addr, read_addr, write_enable, data_in_quantizer)`. These are ports to my `RAM`.
`write_addr` is the address whose width can be changed by the `parameter` `width_addr`(set to 7 now, which needs to be changed to 8) in the `back-end` test bench.

**Comment by cfelton** [comment]
@Vikram9866 and @mkatsimpris 

Have you guys resolved the interface between the frontend and the backend?  I might have missed it in the thread of comments.

From my perspective there seems to be confusion still, per previous discussions the frontend will stream the data (blocks) out after they have been processed (push the data with valid).  The frontend currently doesn't support pausing the flow with the ready signal, it assumes the downstream is always ready (anything incorrect?).

But the backend interfaces is defined as:

```python
def backend(clock, reset, start, data_in, write_addr,
            write_enable, data_out, ready, addr, num_enc_bytes)
```

This does not match what has been described in the discussions or what is in the current code base (frontend):

```python
def frontend_top_level_v2(inputs, outputs, clock, reset, N=8):
```

where `outputs` is:

```python
class outputs_frontend_new(object):

    def __init__(self, precision_factor=10):
        self.out_precision = precision_factor
        self.out_range = 2**precision_factor
        self.data_valid = Signal(bool(0))
        self.end_of_block_conversion = Signal(bool(0))
        self.data_out = Signal(intbv(0, min=-self.out_range, max=self.out_range))
```

I can't resolve the conversations to the actual code, the backend interface looks to expect the upstream (frontend) to fill the RAM (non-streaming, its a port from V1 and not the interfaces we have been discussing this whole project), is this correct?

@mkatsimpris can the `output_frontend` be removed from the code?  It is currently not used, correct?

**Comment by mkatsimpris** [comment]
@cfelton the output_frontend is not used it can be removed. 

I talked with Vikram and he told me that he will change the interface in order to include only the data_in and data_valid and keep the other signals as internal. So we could easily connect the two modules.

Also he stores the data in a RAM so the processing in frontend could be continuous (assuming backend is always ready)

I wait for a complete test with a reference model for his backend otherwise the complete behavior could not be test.

@Vikram9866

**Comment by Vikram9866** [comment]
@cfelton . 
1. We have come to a conculsion that the Front-end will write data continously into a RAM that can hold `3*64 signals`. So, that front-end do not need to stop flow (in the worst case scenario back-end may take 120 cycles).

2. Once the front-end writes a block into the RAM the `connector` between `front-end` and `back-end` will send `start` signal to the `back-end`. The `connector` would not send the `start` signal unless it gets a `ready` signal from the `back-end`. This is the way `back-end` functions.

3. The `connector` will also take data from the front-end and store it in RAM. take the data from RAM and send it to `back-end`.

4. The final structure will be some what like
`def connector(clock, reset, front-end outputs, backend-inputs):`

**Comment by cfelton** [comment]
@Vikram9866 are all the changes complete, is this ready to merge?

**Comment by Vikram9866** [comment]
@cfelton . We dont need connector if I make some internal changes.

**Comment by cfelton** [comment]
@Vikram9866 I am still very confused, can you please explain how you are going to connect the frontend and the backend (please provide a code example or the actual file that would connect them, i.e. the jpegenc top-level).  The comments made in this thread don't appear to be reflected in the code.

```python
backend(clock, reset, start, data_in, write_addr,
 +            write_enable, data_out, ready, addr, num_enc_bytes):
```

Even if we don't get to testing the full encoder the backend and frontend should have compatible interfaces so that they can be connected.

cc: @mkatsimpris

**Comment by Vikram9866** [comment]
@cfelton 

```
# front end interfaces
"""output have output signal and data_valid signal"""

def backend_top(clock, reset, data_in, data_valid, data_out, out_addr):
	"""
	data_in : input data from frontebd
	data_valid : data valid signal from frontend
	data_out : output form backend
	out_addrt : output data address form backend
	"""
	@always_seq(clock.posedge, reset=reset)
	def counter():
		"""this counter increments write address so that
		   front-end writes into Buffer in backend when it have valid data
		"""
		if data_valid:
			write_addr.next = write_addr + 1

	@always_comb()
	def assign():
		"""write enable the data_out"""
		write_enable.next = data_valid

	@always_seq(clock.posedge)
	def start_set():
		"""when backend gets the first block"""
		if wait == 0:
			if write_addr == 63:
				# start the backend when one block is recevied in the buffer
				start.next = True
				wait.next = 1
		else:
			if ready:
				# give start pulse every time the backend sends ready signals
				start.next = True
				wait.next = 1
	inst = backend(clock, reset, start, data_in, write_addr,
            	write_enable, data_out, ready, addr, num_enc_bytes)
	return counter, assign, start_set
```
This is a code sample for the `backend top` which will help `backend` module and `front-end` to connect.
Probably I will make these changes in the back-end itself, so that we dont need to add extra module.

**Comment by cfelton** [comment]
@Vikram9866 why does the output of the backend have and `addr`?  We haven't presumed the downstream is a memory.

**Comment by Vikram9866** [comment]
@cfelton . I have added that just for testing purpose (to see `data_out` at each `addr`). I will remove it.

**Comment by cfelton** [comment]
@Vikram9866 is this PR complete?  Have you committed all the changes discussed above?

**Pull request merged**
